### ISSUE TITLE
Checkpoint placement for Cyber City

### ISSUE THREAD

**Issue by Timothyoung97** [Team-Aston-Martin-Henz/Cyberacer#24]
Checkpoints must be placed such that the player's transform can pass through it. This must be done for all checkpoints. 
Make sure the width is wide enough. (See grey block in pic below)

Else, bugs triggered are:
- Inability to update position properly
- Inability to update lap properly

![image](https://user-images.githubusercontent.com/62177572/123134655-9a550700-d483-11eb-9f65-8b122234e358.png)
*Mesh Render for each checkpoint turned on for better visibility

**Comment by david-eom** [comment]
During user testing, it was found out that `checkpoint 34` in Cyber City need to be re-adjusted. Since the checkpoint itself is in contact with the ground layer instead of the ramp, resetting the car position upon hitting the checkpoint will result in the car being hidden by the ramp itself.
`Checkpoint 34` location:
![截圖 2021-07-22 下午7 11 36](https://user-images.githubusercontent.com/66581587/126630432-76339ad5-6559-44e8-8f89-6a1a2780b95b.png)
Game display:
![截圖 2021-07-22 下午7 10 29](https://user-images.githubusercontent.com/66581587/126630514-fbe8bdd8-1d02-4102-85be-2b403b5e4ba5.png)
